/tracking/verbose 0

#########################
# GPS
/gps/particle proton
/gps/pos/type Point

# Strip Setup
/gps/pos/centre 0.0 0.0 1705.12 mm

/gps/ang/type iso

/gps/ang/mintheta 0
/gps/ang/maxtheta 0.01049961415052362
/gps/ang/minphi 0
/gps/ang/maxphi 6.28318

/gps/direction  0 0 -1

/gps/ene/type User
/gps/hist/type energy
# spectra
/gps/hist/point 200 1

/gps/source/list

/run/beamOn 100000
